$<N_CORRECT_STIM_ITEMS>/<N_TOTAL_STIM_ITEMS>$ ($<PC_STIM_ITEMS>$\%) stim items & $<N_CORRECT_NONSTIM_ITEMS>/<N_TOTAL_NONSTIM_ITEMS>$ ($<PC_NONSTIM_ITEMS>$\%) low biomarker non-stim items & $\chi^2(1)=<CHISQR_STIM_ITEMS>$ & $p=<PVALUE_STIM_ITEMS>$ \\
\hline
$<N_CORRECT_POST_STIM_ITEMS>/<N_TOTAL_POST_STIM_ITEMS>$ ($<PC_POST_STIM_ITEMS>$\%) post-stim items & $<N_CORRECT_NONSTIM_ITEMS>/<N_TOTAL_NONSTIM_ITEMS>$ ($<PC_NONSTIM_ITEMS>$\%) low biomarker non-stim items & $\chi^2(1)=<CHISQR_POST_STIM_ITEMS>$ & $p=<PVALUE_POST_STIM_ITEMS>$ \\
\hline
